services:
  db:
    image: mariadb:10.6.4-focal
    command: "--default-authentication-plugin=mysql_native_password"
    volumes:
      - {{.MOLE_PROJECT_NAME}}-db_data:/var/lib/mysql
      - {{.MOLE_LOG_PATH}}:/var/log
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD={{.MOLE_APP_KEY}}
      - MYSQL_DATABASE={{.MOLE_DB_NAME}}
      - MYSQL_USER={{.MOLE_DB_USER}}
      - MYSQL_PASSWORD={{.MOLE_DB_PASS}}
    networks:
      - {{.MOLE_PROJECT_NAME}}-app_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"

  wordpress:
    image: wordpress:latest
    volumes:
      - {{.MOLE_PROJECT_NAME}}-wp_data:/var/www/html
      - {{.MOLE_LOG_PATH}}:/var/log
      # you should probably mount your theme if you want to include it in the repository:
      # - {{.MOLE_ROOT_PATH}}/mytheme:/var/www/html/wp-content/themes/mytheme
    ports:
      - 127.0.0.1:{{.MOLE_PORT_APP}}:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER={{.MOLE_DB_USER}}
      - WORDPRESS_DB_PASSWORD={{.MOLE_DB_PASS}}
      - WORDPRESS_DB_NAME={{.MOLE_DB_NAME}}
    networks:
      - {{.MOLE_PROJECT_NAME}}-app_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"

volumes:
  {{.MOLE_PROJECT_NAME}}-db_data:
  {{.MOLE_PROJECT_NAME}}-wp_data:

networks:
  {{.MOLE_PROJECT_NAME}}-app_network:
