services:
  db:
    # Use a MariaDB image compatible with amd64 & arm64 architectures
    image: mariadb:10.6.4-focal
    # If you prefer MySQL, uncomment the following line
    # image: mysql:8.0.27
    command: "--default-authentication-plugin=mysql_native_password"
    volumes:
      - {{.MOLE_PROJECT_NAME}}-db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD={{.MOLE_APP_KEY}}
      - MYSQL_DATABASE={{.MOLE_DB_NAME}}
      - MYSQL_USER={{.MOLE_DB_USER}}
      - MYSQL_PASSWORD={{.MOLE_DB_PASS}}
    networks:
      - {{.MOLE_PROJECT_NAME}}-app_network

  wordpress:
    image: wordpress:latest
    volumes:
      - {{.MOLE_PROJECT_NAME}}-wp_data:/var/www/html
    ports:
      - 127.0.0.1:{{.MOLE_PORT_APP}}:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER={{.MOLE_DB_USER}}
      - WORDPRESS_DB_PASSWORD={{.MOLE_DB_PASS}}
      - WORDPRESS_DB_NAME={{.MOLE_DB_NAME}}
    networks:
      - {{.MOLE_PROJECT_NAME}}-app_network

volumes:
  {{.MOLE_PROJECT_NAME}}-db_data:
  {{.MOLE_PROJECT_NAME}}-wp_data:

networks:
  {{.MOLE_PROJECT_NAME}}-app_network:
